language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install flake8
script:
  - pip install Django
  - django-admin.py startproject --template=. myproject
  - cd myproject
  - pip install -r requirements.txt
  - python manage.py syncdb --noinput
  - python manage.py loaddata sites
  - python manage.py validate
  - flake8 myproject
